services:
  frontend:
    depends_on:
      - backend
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: humandbs-dev
    container_name: humandbs-frontend-dev
    volumes:
      - ${PWD}:/app
      - node_modules:/app/node_modules
    environment:
      - HUMANDBS_FRONTEND_HOST=0.0.0.0
      - HUMANDBS_FRONTEND_PORT=3000
    ports:
      - 127.0.0.1:3000:3000
    working_dir: /app
    command: [ "sleep", "infinity" ]
    networks:
      - humandbs-dev-network
    init: true

  backend:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: humandbs-dev
    container_name: humandbs-backend-dev
    volumes:
      - ${PWD}:/app
      - node_modules:/app/node_modules
      # - /lustre9/open/database/ddbjshare/private/ddbj.nig.ac.jp/jga/metadata:/mount/jga-metadata:ro
    environment:
      - HUMANDBS_BACKEND_HOST=0.0.0.0
      - HUMANDBS_BACKEND_PORT=8080
      # - HUMANDBS_BACKEND_JGA_METADATA_DIR=/mount/jga-metadata
    ports:
      - 127.0.0.1:8080:8080
    working_dir: /app
    command: [ "sleep", "infinity" ]
    networks:
      - humandbs-dev-network
    init: true

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.6
    container_name: humandbs-elasticsearch-dev
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - ELASTIC_PASSWORD=humandbs-elasticsearch-dev-password
    ports:
      - "127.0.0.1:9200:9200"
    volumes:
      - ${PWD}/es-data:/usr/share/elasticsearch/data
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    mem_limit: 4g
    networks:
      - humandbs-dev-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.6
    container_name: humandbs-kibana-dev
    environment:
      - ELASTICSEARCH_HOSTS=http://humandbs-elasticsearch-dev:9200
      - ELASTICSEARCH_USERNAME=humandbs-elasticsearch-dev-user
      - ELASTICSEARCH_PASSWORD=humandbs-elasticsearch-dev-password
    ports:
      - "127.0.0.1:5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - humandbs-dev-network

volumes:
  node_modules: {}

networks:
  humandbs-dev-network:
    name: humandbs-dev-network
    external: true
