services:
  cms-db:
    image: docker.io/postgres:17
    container_name: humandbs-cms-db-dev
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - cms_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - humandbs-dev-network
    init: true

  cms-db-migrator:
    image: docker.io/oven/bun:1.3.5
    container_name: humandbs-cms-db-migrator-dev
    environment:
      - POSTGRES_HOST=cms-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    # Mount your app (so drizzle.config.ts, migrations folder, etc. are available)
    volumes:
      - ${PWD}:/app
    working_dir: /app
    depends_on:
      cms-db:
        condition: service_healthy
    entrypoint: ["sleep", "infinity"]
    networks:
      - humandbs-dev-network
    init: true

  frontend:
    depends_on:
      - cms-db
      - backend
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: humandbs-dev
    container_name: humandbs-frontend-dev
    volumes:
      - ${PWD}:/app
      - node_modules:/app/node_modules
      - frontend_node_modules:/app/apps/frontend/node_modules
      - backend_node_modules:/app/apps/backend/node_modules
      - eslint_config_node_modules:/app/packages/eslint-config/node_modules
    environment:
      - HUMANDBS_FRONTEND_HOST=0.0.0.0
      - HUMANDBS_FRONTEND_PORT=3000
      - POSTGRES_HOST=cms-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - HUMANDBS_BACKEND_HOST=backend
      - HUMANDBS_BACKEND_PORT=8080
      - GARAGE_ACCESS_KEY=${GARAGE_ACCESS_KEY}
      - GARAGE_SECRET_KEY=${GARAGE_SECRET_KEY}
      - GARAGE_ENDPOINT=${GARAGE_ENDPOINT}
      - GARAGE_REGION=${GARAGE_REGION}
      - GARAGE_BUCKET_CMS=${GARAGE_BUCKET_CMS}
      - OIDC_ISSUER_URL=https://idp-staging.ddbj.nig.ac.jp/realms/master
      - OIDC_CLIENT_ID=humandbs-dev
      - OIDC_REDIRECT_URI=${OIDC_REDIRECT_URI}
    working_dir: /app
    command: ["sleep", "infinity"]
    networks:
      - humandbs-dev-network
    init: true

  backend:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: humandbs-dev
    container_name: humandbs-backend-dev
    volumes:
      - ${PWD}:/app
      - node_modules:/app/node_modules
      - frontend_node_modules:/app/apps/frontend/node_modules
      - backend_node_modules:/app/apps/backend/node_modules
      - eslint_config_node_modules:/app/packages/eslint-config/node_modules
      # - /lustre9/open/database/ddbjshare/private/ddbj.nig.ac.jp/jga/metadata:/mount/jga-metadata:ro
    environment:
      - HUMANDBS_BACKEND_HOST=0.0.0.0
      - HUMANDBS_BACKEND_PORT=8080
      - GARAGE_ACCESS_KEY=${GARAGE_ACCESS_KEY}
      - GARAGE_SECRET_KEY=${GARAGE_SECRET_KEY}
      - GARAGE_ENDPOINT=${GARAGE_ENDPOINT}
      - GARAGE_REGION=${GARAGE_REGION}
      - GARAGE_BUCKET_DATA=${GARAGE_BUCKET_DATA}
    working_dir: /app
    command: ["sleep", "infinity"]
    networks:
      - humandbs-dev-network
    init: true

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.6
    container_name: humandbs-elasticsearch-dev
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    mem_limit: 4g
    networks:
      - humandbs-dev-network
    init: true

  garage:
    image: dxflrs/garage:v2.2.0
    container_name: humandbs-garage
    restart: unless-stopped
    environment:
      GARAGE_RPC_SECRET: ${GARAGE_RPC_SECRET}
      GARAGE_ALLOW_WORLD_READABLE_SECRETS: true
      GARAGE_LOG_LEVEL: info
    volumes:
      - garage_data:/data
      - garage_meta:/meta
      - ./garage-config.toml:/etc/garage.toml:ro
    networks:
      - humandbs-dev-network
    healthcheck:
      test: ["CMD", "garage", "status"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  nginx:
    image: docker.io/library/nginx:1.27.0
    container_name: humandbs-nginx-dev
    environment:
      - GARAGE_BUCKET_CMS=${GARAGE_BUCKET_CMS}
    volumes:
      - ${PWD}/nginx.conf.template:/etc/nginx/templates/default.conf.template:ro
    ports:
      - 0.0.0.0:5011:80
    networks:
      - humandbs-dev-network
    init: true

volumes:
  node_modules: {}
  frontend_node_modules: {}
  backend_node_modules: {}
  eslint_config_node_modules: {}
  cms_pgdata: {}
  es_data: {}
  garage_data: {}
  garage_meta: {}

networks:
  humandbs-dev-network:
    name: humandbs-dev-network
    external: true
