services:
  frontend:
    depends_on:
      - backend
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: humandbs-dev
    container_name: humandbs-frontend-dev
    volumes:
      - ${PWD}:/app
      - node_modules:/app/node_modules
    environment:
      - HUMANDBS_FRONTEND_HOST=0.0.0.0
      - HUMANDBS_FRONTEND_PORT=3000
    ports:
      - 127.0.0.1:3000:3000
    working_dir: /app
    command: [ "sleep", "infinity" ]
    networks:
      - humandbs-dev-network
    init: true

  backend:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: humandbs-dev
    container_name: humandbs-backend-dev
    volumes:
      - ${PWD}:/app
      - node_modules:/app/node_modules
      # - /lustre9/open/database/ddbjshare/private/ddbj.nig.ac.jp/jga/metadata:/mount/jga-metadata:ro
    environment:
      - HUMANDBS_BACKEND_HOST=0.0.0.0
      - HUMANDBS_BACKEND_PORT=8080
      # - HUMANDBS_BACKEND_JGA_METADATA_DIR=/mount/jga-metadata
    ports:
      - 127.0.0.1:8080:8080
    working_dir: /app
    command: [ "sleep", "infinity" ]
    networks:
      - humandbs-dev-network
    init: true

volumes:
  node_modules: {}

networks:
  humandbs-dev-network:
    name: humandbs-dev-network
    external: true
