FROM oven/bun:1.2-debian

RUN apt update && \
  apt install -y --no-install-recommends \
  curl \
  jq && \
  apt clean && \
  rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .
RUN bun install --frozen-lockfile

EXPOSE 3000
EXPOSE 8080

CMD ["sleep", "infinity"]
